version: "3.8"

services:
  # API Gateway
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zenthia-api-gateway
    ports:
      - "5100:8080"
    restart: unless-stopped
    networks:
      - zenthia-network
networks:
    zenthia-network:
        name: zenthia-network
        driver: bridge
        attachable: true
