version: "3.8"

services:
  # API Gateway
  zenthia-gateway:
    image: ghcr.io/gzidea/zenthia.api.gateway:latest
    container_name: zenthia-gateway
    restart: always
    ports:
      - "5100:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - external_zenthia
networks:
  external_zenthia:
    external: true
