name: Build and Push Docker Image

on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: gzidea/zenthia.api.gateway

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          secrets: |
            github_token=${{ secrets.NUGET_GH_TOKEN }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
      - name: Trigger Portainer redeploy
        env:
          WEBHOOK_URL: ${{ secrets.PORTAINER_WEBHOOK_URL }}
        if: ${{ env.WEBHOOK_URL != '' }}
        run: curl -X POST "$WEBHOOK_URL"
